### ISSUE TITLE
Pretty URLs

### ISSUE THREAD

**Issue by tinzerillo** [nettube/mbtapuller#1]
Remove # from angular routes without removing the ability to copy and paste links

**Comment by mathcolo** [comment]
Speaking of pretty URLs, I'm wondering if the route ids being in URLs means that if the page is bookmarked, and the ids change, the bookmark breaks...probably bad?

**Comment by tinzerillo** [comment]
Good point..we should fix that too

**Comment by mathcolo** [comment]
So removing #s from urls is going to require some web server intervention. At the moment, the #s in urls are being added to prevent the web server (flask) from routing the request elsewhere. This leads to a greater web server discussion...

Right now, all requests are handled as such:

Source -> nginx -> flask

In this configuration, flask is responsible for 100% of requests.

The recommend configuration separates static files from API endpoints, where static files (*.html, *.js, *.css, etc) are served as:

Source -> nginx

And API endpoints are served as:

Source -> nginx -> flask

Accomplishing this would involve removing any Flask templates from any and all html. Not sure how interwoven Flask is into the html right now?

**Comment by tinzerillo** [comment]
The only place it is used, is in the index.html page...kind of heavily used there. We can also go back to investigating other ways of grabbing the route information instead of using the routes passed into flask.

**Comment by tinzerillo** [comment]
NO LONGER NEEDED
