### ISSUE TITLE
Customization features: fav routes, segments, etc

### ISSUE THREAD

**Issue by mathcolo** [nettube/mbtapuller#23]
Convinced that it's valuable to have the ability to customize the UI to show the data I want to see—especially for commute

Way down the line: sign in with Google and it pulls in your work location etc

**Comment by tinzerillo** [comment]
This will be useful when we implement this feature: https://github.com/gsklee/ngStorage

**Comment by tinzerillo** [comment]
Favorite Stations:

Station Cards: Star outline should be added to top-right corner of each and filled in when clicked

Favorites link in sidebar shows cards for all starred stations (sorted by alphabetical order)
  -show next inbound/outbound train services in card?

List of favorited station ids will be stored in local storage

**Comment by tinzerillo** [comment]
#35
