### ISSUE TITLE
Add tooltips to train icons

### ISSUE THREAD

**Issue by tinzerillo** [nettube/mbtapuller#50]
Train at Riverside will have a tooltip (probably popover due to character limits) reading "Train at Riverside" @mathcolo maybe we can come up with a better phrase...not sure I love this
Train between Central and Harvard will have a tooltip reading "Next Stop: Harvard"

**Comment by mathcolo** [comment]
Love the idea—I'm content with any reasonable phrase I think.

Perhaps:
At Riverside
Enroute to Brookline Village

Or even:
At Riverside
Brookline Village in X mins

**Comment by tinzerillo** [comment]
I think at is good. Simple and understandable! I also like the prediction tied in there! Either next stop or prediction sounds good to me

**Comment by mathcolo** [comment]
I can do this once prediction display is up I think!

**Comment by tinzerillo** [comment]
PR #68
