### ISSUE TITLE
Spaces vs tabs cleanup

### ISSUE THREAD

**Issue by mathcolo** [nettube/mbtapuller#57]
Perhaps as a part of cleaning up app.py (?)—files that are a mix of spaces and tabs should ideally become all spaces, since an eventual switch to Python 3.0+ will mean runtime errors instead of warnings (should have used 3 originally, yikes)

Files that include both right now (might be missing some, but I don't think so):
- app.py
- Functions.py

**Comment by tinzerillo** [comment]
🙈🙈

**Comment by tinzerillo** [comment]
PR #59
