### ISSUE TITLE
Predictions display is still incorrect

### ISSUE THREAD

**Issue by mathcolo** [nettube/mbtapuller#61]
I wasn't on target yesterday as much as I thought. Predictions are still wrong, working on it

**Comment by mathcolo** [comment]
Yeah, uh...we just forgot to merge the branch in ✌️

**Comment by tinzerillo** [comment]
Hm?

**Comment by mathcolo** [comment]
What I did over the weekend was correct, I just never PRed so I thought master had the changes in!

**Comment by tinzerillo** [comment]
😂😂😂

**Comment by tinzerillo** [comment]
DUPLICATE OF ISSUE #36
